# Generated by Django 3.1.7 on 2021-03-15 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200)),
                ('carrier', models.CharField(blank=True, default='Sea', max_length=100)),
                ('kind', models.CharField(blank=True, default='Sea', max_length=50)),
                ('weight', models.FloatField(blank=True)),
                ('items', models.IntegerField(blank=True)),
                ('contents', models.TextField(blank=True, default='')),
                ('shipping_cost', models.FloatField(blank=True)),
                ('date_sent', models.DateField(blank=True, verbose_name='date sent')),
                ('date_received_port', models.DateField(blank=True, verbose_name='date received at port')),
                ('date_sent_port', models.DateField(blank=True, verbose_name='date sent from port')),
                ('date_received_destination', models.DateField(blank=True, verbose_name='date received by destination')),
                ('tracking_us', models.CharField(blank=True, default='', max_length=50)),
                ('tracking_international', models.CharField(blank=True, default='', max_length=50)),
                ('delivered', models.BooleanField(blank=True, default='False')),
                ('destination', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.destination')),
            ],
        ),
    ]
