# Generated by Django 3.1.7 on 2021-04-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='date_received_port',
        ),
        migrations.AddField(
            model_name='parcel',
            name='date_arrived_port',
            field=models.DateField(blank=True, null=True, verbose_name='date arrived at port'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='date_arrived_post_office',
            field=models.DateField(blank=True, null=True, verbose_name='date arrived at port'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='date_received_destination',
            field=models.DateField(blank=True, null=True, verbose_name='date received by destination'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='date_sent',
            field=models.DateField(blank=True, null=True, verbose_name='date sent'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='date_sent_port',
            field=models.DateField(blank=True, null=True, verbose_name='date sent from port'),
        ),
    ]
