# Generated by Django 3.1.7 on 2021-04-16 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210416_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='carrier',
            field=models.CharField(blank=True, default='Sea', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='contents',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='delivered',
            field=models.BooleanField(blank=True, default='False', null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.destination'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='items',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='kind',
            field=models.CharField(blank=True, default='Sea', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='shipping_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='tracking_international',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='tracking_us',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
